# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Radio Builder
author: Shadi Youssef                 # syoussef 4/22/2023: added
email: your-email@example.com
github: https://github.com/radiohub   # syoussef 4/22/2023: added

description: >- # this means to ignore newlines until "url:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

url: "https://radiohub.github.com"    # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/radiobuilder"              # the subpath of your site, e.g. /blog syoussef 5/8/2023: forward slash is CRITICAL for local testing!

twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
kramdown:                         # syoussef 4/23/2023: added
  input: GFM                      # Github flavor markdown
  auto_ids: true
  syntax_highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
#  - jekyll-remote-theme          # syoussef 5/7/2023: trying remote themes for Github pages (did not work)

show_excerpts: true               # syoussef 4/22/2023: added
excerpt_separator: <!--more-->    # syoussef 4/23/2023: added

header_pages:
  - design.md
  - help.md
  - about.md

# syoussef 4/24/2023: added
# Default front matter for posts
#defaults:
#  -
#    scope:
#      path: ""
#      type: "posts"
#    values:
#      layout: "post"
#      permalink: "/:categories/:title.html"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
